### PR TITLE
Update to latest Pegdown

### PR DESCRIPTION
**Pull request by Deraen**
This adds support for e.g. strikethroughs.

### CODE REVIEW

**Comment by Deraen** [comment]
I'm also going to add support for all extensions of Pegdown.

**Comment by Deraen** [comment]
Okay more changes.

- Parser extensions can be set
- jTidy was causing problems with some HTML5 tags (such as <figure>) so I removed it and wrote a custom Enlive html tidier for the tests

**Comment by Deraen** [comment]
Because I'm not very happy about how Pegdown wraps headers in anchors, I'm thinking about providing Endophile options for that.

`{:tag :h1, :content [{:tag :a, :attrs {:name "foo" :href "#foo"}, :content ["Foo"]}]}`
it would return
`{:tag :h1, :content [{:tag :a, :attrs {:name "foo"}} "Foo"]}`

**Comment by Deraen** [comment]
Something is currently causing tests to fail in Travis even though they are working for me.

**Comment by Deraen** [comment]
Ah, I forgot. Anchorlinks extension is broken in current Pegdown release (it's erroneously enabled if certain other extensions are enabled). Should be fixed soon.

**Comment by theJohnnyBrown** [comment]
Hi, thanks for taking care of this, I'll go over it as soon as I can. Looking forward to the passing test.

**Comment by Deraen** [comment]
I moved the anchorlinks stuff to another branch so this could be merged now. Looks like it takes some time to get Pegdown changes released.

**Comment by theJohnnyBrown** [comment]
@Deraen, the effort is appreciated. Merging.

**Pull request merged**
