### PR TITLE
Fix MailLinkNode handling for hiccup output

### PR DESCRIPTION
**Pull request by Deraen**

### CODE REVIEW

**Comment by theJohnnyBrown** [comment]
@Deraen I'll deploy the latest today. Just need to do a little dance to recover access to clojars.

**Comment by theJohnnyBrown** [comment]
@Deraen, `0.2.0-SNAPSHOT` is deployed to clojars now

**Comment by Deraen** [comment]
Thanks, just tested and works for me.

Can you deploy proper release also?

**Comment by theJohnnyBrown** [comment]
done

**Pull request merged**
