### PR TITLE
Update Pegdown

### PR DESCRIPTION
**Pull request by Deraen**
Ready to merge

### CODE REVIEW

**Comment by Deraen** [comment]
New pegdown is now released and this works.

**Comment by Deraen** [comment]
Also added new extensions to this PR. New `:extanchorlinks` extensions can be used to change anchorlink format like I has thinking in #9.

**Comment by Deraen** [comment]
@theJohnnyBrown Hi, just remembered this old PR. Pegdown 1.6.0 has been released... a while ago and I just added a few new fixes (#6) and update the dependency versions. Could you merge & deploy this to Clojars?

**Comment by theJohnnyBrown** [comment]
For sure, will do. You should know that this contribution has brightened my day :)

**Comment by Deraen** [comment]
@theJohnnyBrown I just noticed that I forgot to fix the `MailLinkNode` handling for Hiccup version, another PR coming up in a bit.

**Pull request merged**
